### ISSUE TITLE
System crash with NetworkManager

### ISSUE THREAD

**Issue by ghost** [kuba-moo/mt7630e#11]
First, thanks for the drivers.
My system: Archlinux 4.0.1 kernel
Module compile with GCC 5.1
The driver work almost perfectly except below problems:
When I right click on NetworkManager applet on system tray and Uncheck "Enable Wifi" then my system hang. I have to hard reset my system, so I can't collect any log :(

**Comment by kuba-moo** [comment]
Can you try to reproduce this with the `rfkill` command? I think `rfkill block all` should be equivalent of flipping the NM switch.

**Comment by ghost** [comment]
Oh yes, rfkill did it without any problem. But there is one more problem, when I don't use it for a long time (about 30 minutes, I guess), the signal is full, but I can't access the internet, so I try to reconnect it and I can't connect to any Network. Kernel message:
rt2x00lib_rxdone: Error - Wrong frame size 0 max 3840

**Comment by kuba-moo** [comment]
FYI I'm working on mainline support for mt7630e in mt7630e branch of my mt76 repo. I hope I will shake out all the bugs like this in there.
