### ISSUE TITLE
kernel 3.16 and installation failure

### ISSUE THREAD

**Issue by ehood** [kuba-moo/mt7630e#2]
Does the driver support the 3.16 kernel?
Also when trying to install I get this errors- 
ehood@ehood-ubuntu:~/mt7630e$ sudo make install
make -C /lib/modules/`uname -r`/build M=/rt2x00 modules
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-48-generic'
scripts/Makefile.build:44: /rt2x00/Makefile: No such file or directory
make[2]: *** No rule to make target `/rt2x00/Makefile'.  Stop.
make[1]: *** [_module_/rt2x00] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-48-generic'
make: *** [all] Error 2

**Comment by kuba-moo** [comment]
Oh, I didn't use *sudo* to be honest, just assumed it would work :confused: 

Can you try switching to root with *su* and then doing *make install* (without *sudo*)?

**Comment by kuba-moo** [comment]
Turns out **sudo** needs **-s** to function properly in this case, I corrected the instructions. Let me know if the driver works for you now.

**Comment by ehood** [comment]
Thanks, this time there wasn't any errors.
and yet the wireless doesnt working.
any idea why?

**Comment by kuba-moo** [comment]
No problem :) I will close the issue, feel free to reopen if you have any other problems.
