### ISSUE TITLE
Make fails for undeclared identifier

### ISSUE THREAD

**Issue by antipopp** [kuba-moo/mt7630e#21]
This is what I get after running the "make" command:

wookietookie@vassoio:~/mt7630e$ make
make -C /lib/modules/`uname -r`/build M=/home/wookietookie/mt7630e/rt2x00 modules
make[1]: ingresso nella directory "/usr/src/linux-headers-4.2.0-34-generic"
  CC [M]  /home/wookietookie/mt7630e/rt2x00/rt2x00dev.o
  CC [M]  /home/wookietookie/mt7630e/rt2x00/rt2x00mac.o
/home/wookietookie/mt7630e/rt2x00/rt2x00mac.c: In function ‘rt2x00mac_configure_filter’:
/home/wookietookie/mt7630e/rt2x00/rt2x00mac.c:359:6: error: ‘FIF_PROMISC_IN_BSS’ undeclared (first use in this function)
      FIF_PROMISC_IN_BSS;
      ^
/home/wookietookie/mt7630e/rt2x00/rt2x00mac.c:359:6: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:258: set di istruzioni per l'obiettivo "/home/wookietookie/mt7630e/rt2x00/rt2x00mac.o" non riuscito
make[2]: **\* [/home/wookietookie/mt7630e/rt2x00/rt2x00mac.o] Errore 1
Makefile:1398: set di istruzioni per l'obiettivo "_module_/home/wookietookie/mt7630e/rt2x00" non riuscito
make[1]: **\* [_module_/home/wookietookie/mt7630e/rt2x00] Errore 2
make[1]: uscita dalla directory "/usr/src/linux-headers-4.2.0-34-generic"
Makefile:7: set di istruzioni per l'obiettivo "all" non riuscito
make: **\* [all] Errore 2

**Comment by ash0904** [comment]
I am having the same error
