### ISSUE TITLE
bluetooth doesnt work

### ISSUE THREAD

**Issue by fferraro87** [kuba-moo/mt7630e#3]
hi, bluetooth seems that doesnt work. i try to connect my wiimote (like i do on my desktop) with wminput but i've this error:
`Bluetooth device inquiry error`

so i think that ubuntu cannot communicate with bluetooth module, i also try to connect a new device but it cannot find anything. do you've same problem?

**Comment by kuba-moo** [comment]
I tried had a look at it yesterday and I think the Bluetooth stack needs a workaround to communicate with MadiaTek devices. I will try to fix it next week. I don't have access to my testing machine at the moment.

**Comment by sergeyksv** [comment]
@kuba-moo Just want to express my compliments, you make my day :). So far all seems to be working on Asus n751jk and Ubuntu 14.10

**Comment by kuba-moo** [comment]
@fferraro87 I just pushed a commit which adds missing USB ids. Can you check if it helps you?
@sergeyksv Thanks ;)

**Comment by fferraro87** [comment]
@kuba-moo now it works also bluetooth! thanks!!!
