### ISSUE TITLE
windows wifi problems

### ISSUE THREAD

**Issue by fferraro87** [kuba-moo/mt7630e#4]
i've dual boot with windows 8.1 and after that i installed your drivers on ubuntu, when i reboot on windows 8.1, my wifi doesnt work anymore. it start again to work after ten minutes after windows start. i've this error on event viewer : 
`The network adapter with hardware address FC-4D-D4-4E-72-E2 has indicated packet coalescing capability without indicating support for one or more prerequisite receive filter capabilities (IPv6 0x00000000).`

**Comment by neurobin** [comment]
I remember having this problem in windows 8.1, not only wifi, there are bunch of things that don't work with OS transitions, like when I reboot from ubuntu and start windows, it can't detect my headphone sometimes, but after a restart it can. So I think it's not a problem with the driver, rather a problem with the incompatibility between those two Operating Systems.

**Comment by fferraro87** [comment]
i don't know but on my desktop i have no problem with dual boot between this two OS, but on my laptop(hp probook 430 g1) after that i install these drivers, i've this error and only on wifi card so i've thought that there is a connection

**Comment by neurobin** [comment]
The wifi driver available for win 8.1 is troublesome too, I had to install-reinstall several times just to make it work, somehow it managed to not work at a two days period of continuous use.
